[tool.poetry]
name = "dho-scrapy"
version = "0.1.0"
description = ""
authors = ["Bj√∂rn <bjoernwe@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
Scrapy = "^2.7.1"
pydantic = "^1.10.2"
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
